### ISSUE TITLE
Can you add the Zoom Pan and Movable Chart 

### ISSUE THREAD

**Issue by varun2india89** [tiagofumo/flutter-candlesticks-chart#1]
Hello, 
Can you add the Zoom in and Zoom out pan and Also,, Scroll right and left for more timeframe with same Zoom level ?

**Comment by tiagofumo** [comment]
So, I made this in a way that exposes the input values you need so you can do that in your GestureDetector and pass the new series as input. Let's say you zoom in by pinching, then you just pass a new input data series that represents the zoomed data, which has probably a shorter array then the previous one. Same thing with scroll right and left. Let's say you start your app showing the last 60 days, as the user scrolls left you just change the data you send as input to represent a different 60 day window. But you have to build that logic for your specific needs.

**Comment by varun2india89** [comment]
Ok got it, Thanks and I will try on it. 
I am using the Data from Socket to stream inside the chart and I get the below Error, Any help ? 
he following StateError was thrown building CandleStickChart(dirty, state:
_CandleStickChartState#b1c86):
Bad state: No element

Thanks 
Varun

**Comment by tiagofumo** [comment]
I can't say I know what this error is just by that. I will close this issue now then. But if you have any other questions feel free to comment.
